export type ConfigFieldSpec = {
  path: string;
  label: string;
  type: "text" | "number" | "boolean" | "choice" | "number_list";
  description: string;
  example?: string;
  impact?: string;
  options?: string[];
  group?: string;
};

export type ConfigSectionSpec = {
  key: "sumo" | "risk" | "accident" | "output" | "resilience_assessment";
  title: string;
  intro: string;
  fields: ConfigFieldSpec[];
  guide?: {
    title: string;
    overview: string[];
    interpretation: string[];
    references?: string[];
  };
};

const severityTemplates: ConfigFieldSpec[] = ["minor", "moderate", "major", "critical"].flatMap((tier) => {
  const title = `${tier[0].toUpperCase()}${tier.slice(1)} Severity`;
  return [
    {
      path: `accident.severity.${tier}.weight`,
      label: "Selection Weight",
      type: "number" as const,
      group: title,
      description: "Relative probability of selecting this tier when an accident is triggered.",
      example: tier === "minor" ? "62" : "8",
      impact: "Higher values make this severity appear more often across the run.",
    },
    {
      path: `accident.severity.${tier}.duration_min_s`,
      label: "Minimum Duration (s)",
      type: "number" as const,
      group: title,
      description: "Shortest allowed clearance time for this severity tier.",
      example: tier === "minor" ? "120" : "3600",
      impact: "Raising it makes even the best-case incident linger longer.",
    },
    {
      path: `accident.severity.${tier}.duration_max_s`,
      label: "Maximum Duration (s)",
      type: "number" as const,
      group: title,
      description: "Upper bound for sampled duration in this severity tier.",
      example: tier === "minor" ? "900" : "18000",
      impact: "Controls the tail risk of long disruptions.",
    },
    {
      path: `accident.severity.${tier}.lane_capacity_fraction`,
      label: "Lane Capacity Fraction",
      type: "number" as const,
      group: title,
      description: "Share of original lane capacity preserved during the active phase.",
      example: tier === "minor" ? "0.7" : "0.0",
      impact: "Lower values represent harsher blockages and stronger network shock.",
    },
    {
      path: `accident.severity.${tier}.response_time_s`,
      label: "Response Time (s)",
      type: "number" as const,
      group: title,
      description: "How long the incident remains fully active before clearance begins.",
      example: tier === "minor" ? "300" : "1800",
      impact: "Longer response times delay recovery.",
    },
    {
      path: `accident.severity.${tier}.secondary_risk_radius_m`,
      label: "Secondary Risk Radius (m)",
      type: "number" as const,
      group: title,
      description: "Radius around the incident where nearby vehicles inherit elevated accident risk.",
      example: tier === "minor" ? "75" : "500",
      impact: "Larger radii spread disruption to a broader spatial area.",
    },
    {
      path: `accident.severity.${tier}.secondary_risk_multiplier`,
      label: "Secondary Risk Multiplier",
      type: "number" as const,
      group: title,
      description: "Multiplier applied to nearby-vehicle accident risk around the incident.",
      example: tier === "minor" ? "1.5" : "6.0",
      impact: "Higher values make cascade effects more likely.",
    },
  ] as ConfigFieldSpec[];
});

const incidentTemplates: ConfigFieldSpec[] = [
  { index: 0, title: "Baseline", example: "0.0" },
  { index: 1, title: "Low Incident", example: "0.00005" },
  { index: 2, title: "Default Incident", example: "0.00015" },
  { index: 3, title: "High Incident", example: "0.0005" },
  { index: 4, title: "Extreme Incident", example: "0.001" },
].flatMap((scenario) => [
  {
    path: `resilience_assessment.incident_configs.${scenario.index}.name`,
    label: "Scenario Name",
    type: "text" as const,
    group: `Incident Scenario: ${scenario.title}`,
    description: "Label used in reports and comparisons for this incident scenario.",
    example: scenario.title.toLowerCase().replace(/ /g, "_"),
    impact: "Readable names make assessment outputs easier to interpret.",
  },
  {
    path: `resilience_assessment.incident_configs.${scenario.index}.base_probability`,
    label: "Base Probability",
    type: "number" as const,
    group: `Incident Scenario: ${scenario.title}`,
    description: "Baseline accident probability injected into this scenario.",
    example: scenario.example,
    impact: "Higher probabilities create a more stressful resilience test.",
  },
]);

export const CONFIG_SECTIONS: ConfigSectionSpec[] = [
  {
    key: "sumo",
    title: "SUMO Runtime",
    intro:
      "Core simulation engine settings. Use this tab to point SAS to the network, define the run length, and control reproducibility.",
    fields: [
      {
        path: "sumo.config_file",
        label: "SUMO Config File",
        type: "text",
        group: "Network",
        description: "Path to the `.sumocfg` file that defines the network and route files to run.",
        example: "data/cities/thessaloniki/network/thessaloniki.sumocfg",
        impact: "Changing this switches the network context entirely.",
      },
      {
        path: "sumo.binary",
        label: "SUMO Binary",
        type: "choice",
        options: ["sumo", "sumo-gui"],
        group: "Runtime",
        description: "Select headless SUMO or the interactive GUI binary.",
        example: "sumo",
        impact: "`sumo-gui` is useful for inspection; `sumo` is better for automation and batch runs.",
      },
      {
        path: "sumo.total_steps",
        label: "Total Steps",
        type: "number",
        group: "Runtime",
        description: "Total simulated seconds to run before stopping.",
        example: "7200",
        impact: "Higher values produce longer demand horizons and more accumulated incidents.",
      },
      {
        path: "sumo.seed",
        label: "Random Seed",
        type: "number",
        group: "Runtime",
        description: "Primary seed for reproducible route loading and stochastic effects.",
        example: "1",
        impact: "Changing the seed changes specific incident timing and traffic evolution.",
      },
      {
        path: "sumo.step_length",
        label: "Step Length (s)",
        type: "number",
        group: "Runtime",
        description: "Simulation step duration passed to SUMO.",
        example: "5",
        impact: "Shorter steps increase temporal resolution but cost more runtime.",
      },
    ],
  },
  {
    key: "risk",
    title: "Risk Model",
    intro:
      "Defines how exposure becomes accident probability. These parameters change how aggressively speed, density, and local context drive incident triggering.",
    guide: {
      title: "Risk Model Guide",
      overview: [
        "The SAS risk model is a weighted trigger model. At each simulation step, vehicle and road context are converted into a risk score, and that score is compared against the trigger settings in the config.",
        "The important mental model is that `base_probability` sets the global background rate, while the weights and thresholds decide which traffic states become more dangerous than others.",
        "So if you raise `base_probability` you usually raise accidents everywhere; if you change the weights and thresholds you change where and why accidents appear.",
        "In practice, this tab is where you decide whether the simulation should behave like a mostly random incident process or like a traffic-state-sensitive incident process.",
      ],
      interpretation: [
        "`base_probability`: the main global accident-frequency dial. Raising it increases incidents almost everywhere, even before local modifiers are considered.",
        "`speed_weight` and `speed_exponent`: control how strongly fast-moving vehicles become risky. Higher exponents make extreme speeds matter much more than moderate ones.",
        "`speed_variance_weight` and `speed_variance_threshold_ms`: represent instability. They matter when a corridor has abrupt speed differences and stop-start behaviour.",
        "`density_weight` and `peak_density_vehicles_per_km`: represent pressure from crowded conditions. Lowering the peak-density reference makes the same network look more saturated.",
        "`trigger_threshold`: the practical gatekeeper. Lower values make the configured risks trigger more easily.",
        "The road-type multipliers are scenario tuning knobs. They are useful when domain knowledge says intersections, highways, or local streets should systematically carry different risk.",
        "A good operator workflow is to tune one family at a time: first the global rate, then the speed/variance response, then density, then road-type context.",
      ],
      references: [
        "See `docs/REFERENCE.md` for the current risk-model and output conventions.",
        "See `src/sas/core/risk_model.py` for the actual implementation that turns these values into per-vehicle risk.",
      ],
    },
    fields: [
      {
        path: "risk.base_probability",
        label: "Base Probability",
        type: "number",
        group: "Core Risk",
        description: "Baseline per-step accident probability before modifiers are applied.",
        example: "0.000015",
        impact: "This is the main global accident-rate dial.",
      },
      {
        path: "risk.speed_weight",
        label: "Speed Weight",
        type: "number",
        group: "Core Risk",
        description: "Contribution of absolute speed to the risk score.",
        example: "0.4",
        impact: "Higher values punish high-speed behaviour more strongly.",
      },
      {
        path: "risk.speed_exponent",
        label: "Speed Exponent",
        type: "number",
        group: "Core Risk",
        description: "Non-linearity applied to the speed term.",
        example: "2.0",
        impact: "Higher exponents make the highest-speed vehicles disproportionately risky.",
      },
      {
        path: "risk.speed_variance_weight",
        label: "Speed Variance Weight",
        type: "number",
        group: "Core Risk",
        description: "Contribution of local speed instability to the risk score.",
        example: "0.3",
        impact: "Useful when stop-start conditions should increase crash risk.",
      },
      {
        path: "risk.speed_variance_threshold_ms",
        label: "Variance Threshold (m/s)",
        type: "number",
        group: "Core Risk",
        description: "Variance level after which unstable flow starts counting as dangerous.",
        example: "5.0",
        impact: "Lower thresholds make congestion turbulence matter sooner.",
      },
      {
        path: "risk.density_weight",
        label: "Density Weight",
        type: "number",
        group: "Core Risk",
        description: "Contribution of density pressure to the risk score.",
        example: "0.3",
        impact: "Higher values make crowded edges more fragile.",
      },
      {
        path: "risk.peak_density_vehicles_per_km",
        label: "Peak Density (veh/km)",
        type: "number",
        group: "Core Risk",
        description: "Reference density that represents strong pressure on an edge.",
        example: "15",
        impact: "Lowering it makes networks look saturated earlier.",
      },
      {
        path: "risk.trigger_threshold",
        label: "Trigger Threshold",
        type: "number",
        group: "Core Risk",
        description: "Risk score threshold above which an incident may trigger.",
        example: "0.35",
        impact: "Lower thresholds mean accidents trigger more easily.",
      },
      {
        path: "risk.neighbor_radius_m",
        label: "Neighbor Radius (m)",
        type: "number",
        group: "Core Risk",
        description: "Radius used for local neighbourhood context around a vehicle.",
        example: "150",
        impact: "Larger radii smooth local variation and consider wider flow context.",
      },
      {
        path: "risk.road_type_multipliers.highway",
        label: "Highway Multiplier",
        type: "number",
        group: "Road Type Multipliers",
        description: "Multiplier applied on highway-class links.",
        example: "1.5",
      },
      {
        path: "risk.road_type_multipliers.arterial",
        label: "Arterial Multiplier",
        type: "number",
        group: "Road Type Multipliers",
        description: "Multiplier applied on arterial links.",
        example: "1.0",
      },
      {
        path: "risk.road_type_multipliers.local",
        label: "Local Multiplier",
        type: "number",
        group: "Road Type Multipliers",
        description: "Multiplier applied on local streets.",
        example: "0.6",
      },
      {
        path: "risk.road_type_multipliers.intersection",
        label: "Intersection Multiplier",
        type: "number",
        group: "Road Type Multipliers",
        description: "Multiplier applied near intersections and conflict areas.",
        example: "2.0",
      },
    ],
  },
  {
    key: "accident",
    title: "Accident Model",
    intro:
      "Controls how many incidents can exist at once and how severe each one is once triggered. Severity tiers define duration, blockage intensity, and cascade behaviour.",
    guide: {
      title: "Accident Model Guide",
      overview: [
        "The accident model answers what happens after a trigger occurs. It controls concurrency, severity selection, disruption strength, duration, clearance timing, and whether nearby traffic becomes more vulnerable.",
        "The severity tiers are not cosmetic. They determine how strongly a lane is degraded and for how long the shock remains active.",
        "This means two configs can have the same accident count but very different network impact, depending on how aggressive the severity tiers are.",
        "Use this tab when you want to represent light, medium, or severe operational disruption rather than just changing how often incidents happen.",
      ],
      interpretation: [
        "`max_concurrent_accidents`: caps overlap. It prevents unrealistic network-wide collapse caused by too many simultaneous incidents.",
        "`selection weight`: changes how often each severity tier is sampled relative to the others.",
        "`duration_min_s` and `duration_max_s`: define the disruption time range for that tier.",
        "`lane_capacity_fraction`: determines how much of the affected lane remains usable during the active phase.",
        "`response_time_s`: controls how long the incident remains in its strongest blocked state before clearance begins.",
        "`secondary_risk_radius_m` and `secondary_risk_multiplier`: control cascade effects around the incident footprint.",
        "Minor tiers are usually useful for local degradation studies, while major and critical tiers are more important when you want to test recovery, rerouting pressure, and resilience.",
        "If results feel too catastrophic, the first places to inspect are concurrency, lane-capacity fraction, and long-duration major/critical ranges.",
      ],
      references: [
        "See `src/sas/core/accident_manager.py` for the lifecycle implementation.",
        "See `docs/REFERENCE.md` for output artifacts that reflect these choices, including accident reports and antifragility summaries.",
      ],
    },
    fields: [
      {
        path: "accident.max_concurrent_accidents",
        label: "Max Concurrent Accidents",
        type: "number",
        group: "General",
        description: "Upper limit on simultaneously active incidents.",
        example: "4",
        impact: "Prevents the network from collapsing under unrealistic accident stacking.",
      },
      {
        path: "accident.secondary_accident_enabled",
        label: "Enable Secondary Accidents",
        type: "boolean",
        group: "General",
        description: "Allow nearby vehicles to inherit elevated risk around active incidents.",
        example: "true",
        impact: "Turning this on makes cascading disruptions possible.",
      },
      ...severityTemplates,
    ],
  },
  {
    key: "output",
    title: "Outputs & Monitoring",
    intro:
      "Controls what the simulation records and how much live monitoring is produced while a run is active.",
    fields: [
      {
        path: "output.output_folder",
        label: "Output Folder",
        type: "text",
        group: "Artifacts",
        description: "Base directory where run folders and reports are written.",
        example: "results/thessaloniki/default",
        impact: "Separate output roots make comparisons and traceability easier.",
      },
      {
        path: "output.metrics_interval_steps",
        label: "Metrics Interval (steps)",
        type: "number",
        group: "Artifacts",
        description: "How often network metrics are sampled into `network_metrics.csv`.",
        example: "30",
        impact: "Smaller intervals give finer charts and larger files.",
      },
      {
        path: "output.save_vehicle_snapshots",
        label: "Save Vehicle Snapshots",
        type: "boolean",
        group: "Artifacts",
        description: "Persist step snapshots used for visualisations and analysis.",
        example: "true",
      },
      {
        path: "output.save_accident_reports",
        label: "Save Accident Reports",
        type: "boolean",
        group: "Artifacts",
        description: "Write detailed per-accident JSON reports.",
        example: "true",
      },
      {
        path: "output.compute_antifragility_index",
        label: "Compute Antifragility Index",
        type: "boolean",
        group: "Artifacts",
        description: "Compute event-level and aggregate antifragility indicators after the run.",
        example: "true",
      },
      {
        path: "output.save_accident_heatmap",
        label: "Save Accident Heatmap",
        type: "boolean",
        group: "Artifacts",
        description: "Generate the accident spatial heatmap figure.",
        example: "true",
      },
      {
        path: "output.live_progress",
        label: "Enable Live Progress",
        type: "boolean",
        group: "Live Monitoring",
        description: "Continuously refresh the live progress image while a run is active.",
        example: "true",
      },
      {
        path: "output.live_progress_refresh_steps",
        label: "Live Refresh Steps",
        type: "number",
        group: "Live Monitoring",
        description: "How often the live progress image is regenerated.",
        example: "300",
        impact: "Lower values give a smoother dashboard but more plotting overhead.",
      },
      {
        path: "output.pre_window_seconds",
        label: "Pre-window (s)",
        type: "number",
        group: "Analysis Windows",
        description: "Window before an accident used in before/after comparisons.",
        example: "300",
      },
      {
        path: "output.post_window_seconds",
        label: "Post-window (s)",
        type: "number",
        group: "Analysis Windows",
        description: "Window after an accident used in before/after comparisons.",
        example: "300",
      },
      {
        path: "output.baseline_window_steps",
        label: "Baseline Window Steps",
        type: "number",
        group: "Analysis Windows",
        description: "Historical window used to infer pre-incident baseline performance.",
        example: "3600",
      },
    ],
  },
  {
    key: "resilience_assessment",
    title: "Resilience Assessment",
    intro:
      "Batch-assessment settings for scenario sweeps, parallel workers, scenario definitions, and composite resilience scoring.",
    guide: {
      title: "Resilience Assessment Guide",
      overview: [
        "The resilience assessment runs structured batches instead of a single scenario. It varies demand and incident settings, then aggregates behaviour into resilience and antifragility outputs.",
        "This part of the config is less about one simulation and more about the design of the experiment you want SAS to execute.",
        "A good way to read this tab is: execution settings, stress ladder, incident ladder, and reporting weights.",
        "If the normal simulation config defines one world, the resilience-assessment config defines the matrix of worlds that the assessment will generate and compare.",
      ],
      interpretation: [
        "`demand_levels`: the stress ladder. Wider ranges are useful when you want to detect breakpoints between resilient and failing behaviour.",
        "`seeds_per_scenario` and `base_seed`: control how much replication you want before trusting aggregate patterns.",
        "`incident_configs`: define the named incident scenarios that will be compared in the assessment outputs.",
        "`resilience_weights`: decide how much speed, throughput, recovery, and robustness contribute to the composite resilience score in reports.",
        "`top_weak_points`: only affects reporting depth, not the simulation itself.",
        "Use fewer demand levels and fewer seeds when you need fast exploratory work; use broader ladders and more seeds when you want stable comparative evidence.",
        "The incident-scenario rows should usually move from baseline to progressively harsher conditions so the resulting report reads as a clear stress progression.",
      ],
      references: [
        "See `src/sas/analysis/resilience_assessment.py` for the batch orchestration and summary logic.",
        "See the generated assessment report and `docs/REFERENCE.md` for the result artifacts produced by these runs.",
      ],
    },
    fields: [
      {
        path: "resilience_assessment.max_workers",
        label: "Max Workers",
        type: "number",
        group: "Execution",
        description: "Maximum number of parallel workers for assessments. Leave empty to auto-select.",
        example: "4",
      },
      {
        path: "resilience_assessment.base_port",
        label: "Base Port",
        type: "number",
        group: "Execution",
        description: "Starting port used when multiple SUMO workers are launched.",
        example: "10000",
      },
      {
        path: "resilience_assessment.demand_levels",
        label: "Demand Levels",
        type: "number_list",
        group: "Execution",
        description: "Demand multipliers tested across the resilience assessment, entered as an ordered vertical list so the stress ladder remains readable and easy to verify.",
        example: "0.5, 0.75, 1.0, 1.5, 2.0",
        impact: "Wider ranges reveal where the network leaves the resilient regime.",
      },
      {
        path: "resilience_assessment.seeds_per_scenario",
        label: "Seeds Per Scenario",
        type: "number",
        group: "Execution",
        description: "How many replicate runs are executed for each demand/incident scenario.",
        example: "3",
      },
      {
        path: "resilience_assessment.base_seed",
        label: "Base Seed",
        type: "number",
        group: "Execution",
        description: "Seed offset for assessment scenario generation.",
        example: "42",
      },
      {
        path: "resilience_assessment.resilience_weights.speed",
        label: "Speed Weight",
        type: "number",
        group: "Composite Score Weights",
        description: "Weight assigned to speed resilience in the composite score.",
        example: "0.3",
      },
      {
        path: "resilience_assessment.resilience_weights.throughput",
        label: "Throughput Weight",
        type: "number",
        group: "Composite Score Weights",
        description: "Weight assigned to throughput maintenance.",
        example: "0.25",
      },
      {
        path: "resilience_assessment.resilience_weights.recovery",
        label: "Recovery Weight",
        type: "number",
        group: "Composite Score Weights",
        description: "Weight assigned to recovery after disruption.",
        example: "0.25",
      },
      {
        path: "resilience_assessment.resilience_weights.robustness",
        label: "Robustness Weight",
        type: "number",
        group: "Composite Score Weights",
        description: "Weight assigned to baseline robustness.",
        example: "0.2",
      },
      {
        path: "resilience_assessment.top_weak_points",
        label: "Top Weak Points",
        type: "number",
        group: "Reporting",
        description: "How many vulnerable edges to highlight in reports.",
        example: "10",
      },
      ...incidentTemplates,
    ],
  },
];
